apiVersion: apps/v1

kind: Deployment

metadata:

  name: ping-service-deployment

  labels:

    app: ping-service

spec:

  replicas: 1

  selector:

    matchLabels:

      app: ping-service

  template:

    metadata:

      labels:

        app: ping-service

    spec:

      containers:

      - name: app

        image: ping-service
        imagePullPolicy: IfNotPresent

        env:
          - name: URL
            value: http://www.google.com
